from typing import Protocol


class IChatSourceRepository(Protocol):
    def sample(self, office_id: str, voice_id: str) -> dict | None: ...
    def language_active(self, unique_id: str) -> bool: ...
    def input_file(self, office_id: str, message_id: str) -> dict | None: ...
    def create_input(self, office_id: str, user_id: str, message_id: str, metadata: dict) -> None: ...
