from typing import Protocol

from app.entities.dubbing_job.job_lease_entity import JobLeaseEntity


class IJobExecutionRepository(Protocol):
    def claim(self, token: str, lease_seconds: int, max_attempts: int) -> JobLeaseEntity | None: ...
    def renew(self, lease: JobLeaseEntity, lease_seconds: int) -> bool: ...
    def recover(self, max_attempts: int) -> int: ...
    def fail(self, lease: JobLeaseEntity, code: str) -> bool: ...
