from typing import ContextManager, Protocol


class IPrivateMediaStorage(Protocol):
    def publication(self) -> ContextManager[bool]: ...
    def save(self, office_id: str, file_id: str, content: bytes) -> str: ...
    def path(self, key: str) -> str: ...
