from typing import Protocol


class ISampleRepository(Protocol):
    def register(self, office_id: str, voice_id: str, user_id: str, metadata: dict) -> dict: ...
    def list(self, office_id: str, voice_id: str, limit: int, offset: int) -> list[dict]: ...
    def find_file(self, office_id: str, voice_id: str, sample_id: str) -> str | None: ...
