from typing import Protocol

from app.entities.dubbing_job.dubbing_job_entity import DubbingJobEntity


class IJobRepository(Protocol):
    def lock_owner(self, office_id: str, owner_id: str) -> None: ...
    def by_key(self, office_id: str, owner_id: str, key: str) -> DubbingJobEntity | None: ...
    def find(self, office_id: str, unique_id: str) -> DubbingJobEntity | None: ...
    def create(self, entity: DubbingJobEntity) -> None: ...
    def cancel(self, office_id: str, unique_id: str) -> None: ...

    def chat_has_work(self, office_id: str, chat_id: str) -> bool: ...

    def list_chat(
        self, office_id: str, owner_id: str, chat_id: str, limit: int, offset: int
    ) -> list[DubbingJobEntity]: ...
