from typing import Protocol

from app.entities.project_audio_link.project_audio_link_entity import ProjectAudioLinkEntity


class IProjectAudioLinksRepository(Protocol):
    def owned_audio(self, office_id: str, owner_id: str, output_id: str) -> str | None: ...
    def list(
        self, office_id: str, user_id: str, project_id: str, limit: int, offset: int
    ) -> list[ProjectAudioLinkEntity]: ...
    def find(self, office_id: str, project_id: str, media_id: str) -> ProjectAudioLinkEntity | None: ...
    def find_id(self, office_id: str, unique_id: str) -> ProjectAudioLinkEntity | None: ...
    def save(self, entity: ProjectAudioLinkEntity, create: bool) -> None: ...
