from __future__ import annotations

from typing import Protocol

from app.entities.tag.tag_entity import TagEntity


class ITagsRepository(Protocol):
    def list(self, office_id: str, limit: int, offset: int) -> list[TagEntity]: ...
    def find(self, office_id: str, unique_id: str) -> TagEntity | None: ...
    def save(self, entity: TagEntity, create: bool) -> None: ...
    def voice_exists(self, office_id: str, voice_id: str) -> bool: ...
    def list_voice(self, office_id: str, voice_id: str) -> list[TagEntity]: ...
    def replace_voice(self, office_id: str, voice_id: str, tag_ids: tuple[str, ...]) -> None: ...
